name: 빌드

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: MacOS
    runs-on: macos-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure Executable Permissions
        run: |
          chmod +x assets/bin/xdelta3_mac || true
          chmod +x build.sh || true

      - name: macOS 앱 빌드
        run: |
          pyinstaller --noconfirm DELTARUNE_KR_Patcher.spec

      - name: 압축 (macOS App Bundle)
        run: |
          cd dist
          zip -9 -r "Patcher_macOS.zip" "Patcher.app"

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: dist/Patcher_macOS.zip

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: AppImage 도구 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 desktop-file-utils
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool

      - name: 빌드 스크립트 실행
        run: |
          chmod +x build.sh
          ./build.sh

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: |
            dist/Patcher.AppImage
            dist/Patcher

  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 빌드
        run: |
          .\build.bat
        shell: cmd

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: dist/Patcher.exe
