name: 빌드

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 러스트 설치
        uses: dtolnay/rust-toolchain@stable

      - name: 러스트 캐시 설치
        uses: Swatinem/rust-cache@v2

      - name: 의존성 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 desktop-file-utils build-essential pkg-config libx11-dev libxcb1-dev libxcursor-dev libxinerama-dev libxi-dev libxrandr-dev libfontconfig1-dev

      - name: 빌드
        run: |
          chmod +x build.sh
          ./build.sh

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Packages
          path: |
            dist/Linux-Patcher.AppImage
            dist/Linux-Patcher-bin

  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 러스트 툴체인 설치
        uses: dtolnay/rust-toolchain@stable

      - name: 러스트 캐시 설치
        uses: Swatinem/rust-cache@v2

      - name: 빌드
        run: |
          chmod +x build.sh
          ./build.sh

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Package
          path: dist/MacOS-Patcher.app

  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 러스트 툴체인 설치
        uses: dtolnay/rust-toolchain@stable

      - name: 러스트 캐시 설치
        uses: Swatinem/rust-cache@v2

      - name: 빌드
        run: |
          .\build.bat
        shell: cmd

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Package
          path: dist/Windows-Patcher.exe
